---
title: "Clustering"
output: html_document
date: '2024-03-25'
---

```{r setup-chunk, include=FALSE}
knitr::opts_chunk$set(dev = "jpg",
                      dpi = 300,
                      cache = TRUE)
```

```{r}
# Libraries, working directory etc.
setwd("~/Desktop/Trio data/")
# rm(list = ls())
library(tidyverse)
library(gridExtra)
library(ggplot2)
library(readr)
library(gtools)
library(dplyr)
library(lsa)
theme_set(theme_bw())
```

```{r}
# Loading Poisson update function and NB update function
source("~/Desktop/Trio data/Poisson updates function.R")
```

```{r}
# Loading the trio data
load("filtered_data_pat.RData")
load("filtered_data_mat.RData")

# Loading the matrices grouped by parents age with 40 groups
pat_data_matrix_40 <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_PaternalMutations_grouped_40.rds")
mat_data_matrix_40 <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_MaternalMutations_grouped_40.rds")

# Loading the matrices grouped by parents age with 119 groups
pat_data_matrix_119 <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_PaternalMutations_grouped_119.rds")
mat_data_matrix_119 <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_MaternalMutations_grouped_119.rds")

# Loading the full data matrices
full_pat_data_matrix <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_PaternalMutations.rds")
full_mat_data_matrix <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_MaternalMutations.rds")
```


```{r}
# Making the hierarchical clusters
hc.complete <- hclust(dist(full_pat_data_matrix), method = "complete")
hc.average <- hclust(dist(full_pat_data_matrix), method = "average")
hc.single <- hclust(dist(full_pat_data_matrix), method = "single")
```


```{r}
# Add a column with a color depending on the age of the father

pat_data_clust <- filtered_data_pat %>% group_by(Child, AGE_FATHER, AGE_MOTHER) %>% summarise(total_count = length(Pos))
# Define the range of ages
min_age <- min(pat_data_clust$AGE_FATHER)
max_age <- max(pat_data_clust$AGE_FATHER)
min_age_mat <- min(pat_data_clust$AGE_MOTHER)
max_age_mat <- max(pat_data_clust$AGE_MOTHER)

# Custom function to generate a color gradient
generate_gradient <- function(age) {
  # Normalize age between 0 and 1
  normalized_age <- (age - min_age) / (max_age - min_age)
  # Generate gradient from light yellow to dark red
  gradient <- rgb(255, 255 * (1 - normalized_age), 0, maxColorValue = 255)
  return(gradient)
}

# Custom function to generate a color gradient
generate_gradient_mat <- function(age) {
  # Normalize age between 0 and 1
  normalized_age <- (age - min_age_mat) / (max_age_mat - min_age_mat)
  # Generate gradient from light yellow to dark red
  gradient <- rgb(255, 255 * (1 - normalized_age), 0, maxColorValue = 255)
  return(gradient)
}

# Add a column with colors based on the age of the father
pat_data_clust <- pat_data_clust %>%
  mutate(colour = generate_gradient(AGE_FATHER), colour_mat = generate_gradient_mat(AGE_MOTHER))
```


```{r, fig.width= 10, fig.height=3.5}
par(mai = c(0.5,0.5,0.3,0.05), mfrow = c(1,3),cex = 1 ,mgp = c(1.5, 0.5, 0))
plot(pat_data_clust$AGE_FATHER, col = pat_data_clust$colour)
ggplot(pat_data_clust, aes(x = AGE_FATHER, y = total_count)) +
  geom_point(col = pat_data_clust$colour) + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
```

```{r, fig.width= 10, fig.height=3.5}
par(mai = c(0.5,0.5,0.3,0.05), mfrow = c(1,3),cex = 1 ,mgp = c(1.5, 0.5, 0))
ggplot(pat_data_clust, aes(x = AGE_MOTHER, y = total_count)) +
  geom_point(col = pat_data_clust$colour_mat) + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
```



```{r, fig.width= 10, fig.height=3.5}
par(mai = c(0.5,0.5,0.3,0.05), mfrow = c(2,1),cex = 1 ,mgp = c(1.5, 0.5, 0))
library(dendextend)

# Create the dendrograms
hc.complete <- hclust(dist(full_pat_data_matrix), method = "complete")
hcd_comp <- as.dendrogram(hc.complete)
hc.average <- hclust(dist(full_pat_data_matrix), method = "average")
hcd_avg <- as.dendrogram(hc.average)

# Extract the child IDs from the dendrogram
dend_ids <- labels(hcd_comp)
dend_ids_avg <- labels(hcd_avg)


# Match child IDs from the dendrogram with pat_data_clust
matched_rows <- match(dend_ids, pat_data_clust$Child)
matched_rows_avg <- match(dend_ids_avg, pat_data_clust$Child)

# Extract colors for the father's age based on matched rows
branch_colors <- pat_data_clust$colour[matched_rows]
branch_colors_avg <- pat_data_clust$colour[matched_rows_avg]

# Similarly for the mother's age
branch_colors_mat <- pat_data_clust$colour_mat[matched_rows]
branch_colors_avg_mat <- pat_data_clust$colour_mat[matched_rows_avg]


# Color the branches using the extracted colors
dend_comp <- color_branches(hcd_comp, col = branch_colors)
dend_avg <- color_branches(hcd_avg, col = branch_colors_avg)

dend_comp_mat <- color_branches(hcd_comp, col = branch_colors_mat)
dend_avg_mat <- color_branches(hcd_avg, col = branch_colors_avg_mat)

# Plot the dendrogram
#plot(dend_comp)
#plot(dend_avg)

# This is to make it in the right order!! 
pat_data_clust <- pat_data_clust %>% arrange(AGE_FATHER)
ordered_hcd <- reorder(dend_avg, pat_data_clust$AGE_FATHER)
ordered_comp <- reorder(dend_comp, pat_data_clust$AGE_FATHER)

# For mat
pat_data_clust <- pat_data_clust %>% arrange(AGE_MOTHER)
ordered_hcd_mat <- reorder(dend_avg_mat, pat_data_clust$AGE_MOTHER)
ordered_comp_mat <- reorder(dend_comp_mat, pat_data_clust$AGE_MOTHER)
plot(ordered_hcd)
plot(ordered_hcd_mat)
# plot(ordered_comp)
```




# This is to look at the outliers
```{r, fig.width= 10, fig.height=3.5}
par(mai = c(0.5,0.5,0.3,0.05), mfrow = c(2,1), cex = 1, mgp = c(1.5, 0.5, 0))
# Which ones are the small clusters in the top???
cut <- cutree(ordered_hcd, k = 2)

# Which are the ones sorted into cluster 2?
cut[cut==2]

# Finding their information
pat_data_clust[which(pat_data_clust$Child == 106822),]
pat_data_clust[which(pat_data_clust$Child == 144956),]

# The two above are sorted in their own cluster. Why? Maybe make a plot with age/number of mutations, and color these two points in their own color
pat_data_clust$colour <- ifelse(pat_data_clust$Child == 106822, "Green",
                                ifelse(pat_data_clust$Child == 144956, "Red", "Black"))

# Overall plot of mutations - here we don't see a reason why those two should be clustered together
ggplot(pat_data_clust, aes(x = AGE_FATHER, y = total_count)) + geom_point(colour = pat_data_clust$colour) +
  theme_minimal() +
  theme(axis.text = element_text(size = 18), axis.title = element_text(size = 18)) + 
  labs(x = "Age of father", y = "Number of mutations")


# Going into details on the mutation types
filtered_data_pat_clust <- filtered_data_pat %>% group_by(Child, AGE_FATHER, mutation_class_cpg) %>% summarise(count_mutation = length(mutation_class_cpg))

for (i in unique(filtered_data_pat_clust$mutation_class_cpg)){
  print(i)
  mean_type <- median(filtered_data_pat_clust$count_mutation[filtered_data_pat_clust$mutation_class_cpg == i]) 
  mutation_count_value_1 <- filtered_data_pat_clust$count_mutation[
    filtered_data_pat_clust$Child == 106822 &
    filtered_data_pat_clust$mutation_class_cpg == i]
  mutation_count_value_2 <- filtered_data_pat_clust$count_mutation[
    filtered_data_pat_clust$Child == 144956 &
    filtered_data_pat_clust$mutation_class_cpg == i]
  print("Median number of mutations:")
  print(mean_type)
  print("Number of mutations for cluster:")
  print(mutation_count_value_1)
  print(mutation_count_value_2)
}

# They are both low on C>G mutations and have a high number of T>C mutations
```



```{r}
## Checking the odd ones out by cosine similarity
child1 <- full_pat_data_matrix["106822",]
child2 <- full_pat_data_matrix["144956",]
mean_all <- apply(full_pat_data_matrix,2,mean)

cosine(child1, child2) # 0.57
cosine(child1, mean_all) # 0.61
cosine(child2, mean_all) # 0.39
```

