---
title: "Trio data intro"
output: html_document
date: '2024-04-29'
---

This document contains code for the introduction plots to the data

```{r setup, include=FALSE}
# To set a seed used for all. There is random initialization in the update functions
knitr::opts_chunk$set(seed = 123)
```

```{r}
# Libraries, working directory etc.
setwd("~/Desktop/Trio data/")
rm(list = ls())
library(tidyverse)
library(gridExtra)
library(ggplot2)
library(readr)
library(gtools)
library(dplyr)
library(lsa)
theme_set(theme_bw())
# Library for Hungarian method
library(clue)
```

```{r}
# Loading Poisson update function as well as other useful functions
source("~/Desktop/Trio data/Poisson updates function.R")
```

```{r}
# Loading the trio data
load("filtered_data_pat.RData")
load("filtered_data_mat.RData")

# Loading the matrices grouped by parents age with groups
pat_data_matrix_grouped <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_PaternalMutations_grouped.rds")
mat_data_matrix_grouped <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_MaternalMutations_grouped.rds")


# Loading the full data matrices
full_pat_data_matrix <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_PaternalMutations.rds")
full_mat_data_matrix <- readRDS("/Users/idajorgensen/Desktop/Trio data/CountMat_MaternalMutations.rds")

# COSMIC signatures
COSMIC_v3.3.1_SBS_GRCh37 <- read.delim("~/Desktop/Trio data/COSMIC_v3.3.1_SBS_GRCh37.txt")
```


First we look at the spread of the children in regards to the ages of the parents
```{r}
# To see spread of children regarding age of the parents
plotdata <- filtered_data_pat %>% group_by(Child, AGE_MOTHER, AGE_FATHER) %>% summarise(count = length(Pos))
ggplot(plotdata, aes(x = AGE_FATHER, y = AGE_MOTHER)) +
  geom_point() +
  labs(title = "Age", x = "Age of father", y = "Age of mother") + geom_jitter(width = 0.5, height = 0.5) +
  theme_minimal() + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
```


## Paternal data
Looking into the sparseness of the data
```{r}
# How many of the data entries are zero

print("Percentage of zero entries in paternal data matrix with groups")
sum(pat_data_matrix_grouped==0)/(nrow(pat_data_matrix_grouped)*ncol(pat_data_matrix_grouped))*100


print("Percentage of zero entries in full paternal data matrix")
sum(full_pat_data_matrix==0)/(nrow(full_pat_data_matrix)*ncol(full_pat_data_matrix))*100

```

Distribution of the ages of the fathers
```{r}
plotdata_pat <- filtered_data_pat %>% group_by(AGE_FATHER) %>% summarise(children = length(unique(Child)))
p_pat <- ggplot(plotdata_pat, aes(x = AGE_FATHER, y = children)) +
  geom_bar(stat = "identity") +
  labs(x = "Age of father", y = "Number of children") + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
p_pat
```

```{r}
# Average number of mutations passed along from father
print("Average number of mutations passed along from the father")
length(filtered_data_pat$Pos)/length(unique(filtered_data_pat$Child))

print("Minimum paternal age")
min(filtered_data_pat$AGE_FATHER)
print("Maximum paternal age")
max(filtered_data_pat$AGE_FATHER)
```

```{r}
# To check for age trend in paternal data
age_pat <- filtered_data_pat %>% group_by(AGE_FATHER) %>% summarise(count = length(Pos), children = length(unique(Child)))
ageplot_pat <- ggplot(age_pat, aes(x = AGE_FATHER, y = count/children)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  geom_text(aes(label = paste("Intercept:", round(coef(lm(count/children ~ AGE_FATHER, data = age_pat))[1], 2), "Slope:", round(coef(lm(count/children ~ AGE_FATHER, data = age_pat))[2], 2))), x = -Inf, y = Inf, hjust = 0, vjust = 1, size = 5) + 
  labs(title = "Number of mutations per father that age", x = "Age of father", y = "Number of mutations per father") +
  theme_minimal() + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
ageplot_pat
```



## Maternal data


```{r}
# How many of the data entries are zero

print("Percentage of zero entries in maternal data matrix with groups")
sum(mat_data_matrix_grouped==0)/(nrow(mat_data_matrix_grouped)*ncol(mat_data_matrix_grouped))*100

print("Percentage of zero entries in full maternal data matrix")
sum(full_mat_data_matrix==0)/(nrow(full_mat_data_matrix)*ncol(full_mat_data_matrix))*100
```


Distribution of the ages of the mothers
```{r}
plotdata_mat <- filtered_data_pat %>% group_by(AGE_MOTHER) %>% summarise(children = length(unique(Child)))
p_mat <- ggplot(plotdata_mat, aes(x = AGE_MOTHER, y = children)) +
  geom_bar(stat = "identity") + 
  labs(x = "Age of mother", y = "Number of children") + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
p_mat
```


```{r}
# Average number of mutations passed along from mother
print("Average number of mutations passed along from the mother")
length(filtered_data_mat$Pos)/length(unique(filtered_data_mat$Child))

print("Minimum maternal age")
min(filtered_data_mat$AGE_MOTHER)
print("Maximum maternal age")
max(filtered_data_mat$AGE_MOTHER)
   
```


```{r}
# To check for age trend in maternal data
age_mat <- filtered_data_mat %>% group_by(AGE_MOTHER) %>% summarise(count = length(Pos), children = length(unique(Child)))
ageplot_mat <- ggplot(age_mat, aes(x = AGE_MOTHER, y = count/children)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  geom_text(aes(label = paste("Intercept:", round(coef(lm(count/children ~ AGE_MOTHER, data = age_mat))[1], 2), "Slope:", round(coef(lm(count/children ~ AGE_MOTHER, data = age_mat))[2], 2))), x = -Inf, y = Inf, hjust = 0, vjust = 1, size = 5) + 
  labs(title = "Number of mutations per mother that age", x = "Age of mother", y = "Number of mutations per mother") +
  theme_minimal() + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))
ageplot_mat
```