---
title: "Trio data management"
output: html_document
date: '2024-02-28'
---

```{r}
# Libraries, working directory etc.
setwd("~/Desktop/Trio data/")
rm(list = ls())
library(readr)
library(gtools)
library(dplyr)
theme_set(theme_bw())
```


```{r}
# Prepare data - maternal mutations ####

# Loading data
mat_data <- read_tsv("maternal_dnms_transition_transversion.tsv", col_names = F)

# Giving column names
colnames(mat_data) <- c("Chr",	"Pos",	"Ref",	"Alt",	"mutation_class_cpg",	
                        "Type_of_mutation",	"context",	"Child",	"Phase", 
                        "AGE_FATHER",	"AGE_MOTHER")

# Changing to correct mutation terminology
mat_data$mutation_class_cpg[mat_data$mutation_class_cpg=="CpG>TpG"] <- "C>T"
mat_data$mutationtype <- apply(mat_data,1,function(x) paste0(substr(x[7],1,1), "[", x[5], "]", substr(x[7],3,3)))
```


```{r}
# Prepare data - paternal mutations ####

# Loading data
pat_data <- read_tsv("paternal_dnms_transition_transversion.tsv", col_names = F)

# Giving column names
colnames(pat_data) <- c("Chr",	"Pos",	"Ref",	"Alt",	"mutation_class_cpg",	
                        "Type_of_mutation",	"context",	"Child",	"Phase", 
                        "AGE_FATHER",	"AGE_MOTHER")

# Changing to correct mutation terminology
pat_data$mutation_class_cpg[pat_data$mutation_class_cpg=="CpG>TpG"] <- "C>T"
pat_data$mutationtype <- apply(pat_data,1,function(x) paste0(substr(x[7],1,1), "[", x[5], "]", substr(x[7],3,3)))

## It is seen by the number of children, that they do not correspond for the paternal and maternal data. 
## We thus below find those that are not present in both. This is only the case for children registered in the paternal data and not in the maternal data. This corresponds to 53 children.

# Find elements that are the same in both lists (intersection)
common_children <- intersect(unique(pat_data$Child), unique(mat_data$Child))

# We only keep the children present in both data sets
pat_data <- pat_data[pat_data$Child %in% common_children, ]
```

```{r}
# We need to drag out the data that has grandparent data as well. Could be done with k-means, as we don't have any indicator
set.seed(123)

pat_data3 <- pat_data %>% group_by(Child, AGE_FATHER, AGE_MOTHER) %>% summarise(total_count = length(Pos))

# Setting the number to 5 from graphical representation
k <- 5

kmeans_result <- kmeans(pat_data3[, c("AGE_FATHER", "total_count", "AGE_MOTHER")], centers = k)
pat_data3$cluster <- as.factor(kmeans_result$cluster)

# Plot to see if it seems reasonable
ggplot(pat_data3, aes(x = pat_data3$AGE_FATHER, y = pat_data3$total_count, col = cluster)) + geom_point() +
  labs(title = "Splitting 2 generations from 3 generations", x = "Age of father", y = "Number of mutations") + 
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14))

# Merge pat_data with pat_data3 based on Child
merged_data_pat <- inner_join(pat_data, pat_data3 %>% select(Child, cluster), by = "Child")
merged_data_mat <- inner_join(mat_data, pat_data3 %>% select(Child, cluster), by = "Child")

# Remove redundant columns added from the "join"
merged_data_pat <- merged_data_pat %>%
  select(-AGE_FATHER.y)
merged_data_mat <- merged_data_mat %>%
  select(-AGE_FATHER.y)
colnames(merged_data_pat)[which(names(merged_data_pat) == "AGE_FATHER.x")] <- "AGE_FATHER"
colnames(merged_data_mat)[which(names(merged_data_mat) == "AGE_FATHER.x")] <- "AGE_FATHER"

# Filter rows where the cluster is 1, 3, or 5
filtered_data_pat <- merged_data_pat %>%
  filter(cluster %in% c(1, 3, 5))
filtered_data_mat <- merged_data_mat %>%
  filter(cluster %in% c(1, 3, 5))
```


## Making the matrices with 40 groups!
```{r}
# As we have very small counts, we will divide the data into grids. Here for both types of mutations

# Create the bins for mother and father
age_mother_bins_pat_40 <- seq(min(filtered_data_pat$AGE_MOTHER)-1, max(filtered_data_pat$AGE_MOTHER)+5, by = 6)
age_father_bins_pat_40 <- seq(min(filtered_data_pat$AGE_FATHER)-1, max(filtered_data_pat$AGE_FATHER)+5, by = 6)

age_mother_bins_mat_40 <- seq(min(filtered_data_mat$AGE_MOTHER)-1, max(filtered_data_mat$AGE_MOTHER)+5, by = 6)
age_father_bins_mat_40 <- seq(min(filtered_data_mat$AGE_FATHER)-1, max(filtered_data_mat$AGE_FATHER)+5, by = 6)

# Cut age values into bins
filtered_data_pat$age_mother_group_40 <- cut(filtered_data_pat$AGE_MOTHER, breaks = age_mother_bins_pat_40, labels = FALSE)
filtered_data_pat$age_father_group_40 <- cut(filtered_data_pat$AGE_FATHER, breaks = age_father_bins_pat_40, labels = FALSE)

filtered_data_mat$age_mother_group_40 <- cut(filtered_data_mat$AGE_MOTHER, breaks = age_mother_bins_mat_40, labels = FALSE)
filtered_data_mat$age_father_group_40 <- cut(filtered_data_mat$AGE_FATHER, breaks = age_father_bins_mat_40, labels = FALSE)

# Now 'age_mother_group' and 'age_father_group' columns contain the group membership based on the grid

# Combine grid memberships from both age_mother_group and age_father_group columns
filtered_data_pat$combined_group_40 <- paste(filtered_data_pat$age_mother_group_40, filtered_data_pat$age_father_group_40, sep = "-")
filtered_data_mat$combined_group_40 <- paste(filtered_data_mat$age_mother_group_40, filtered_data_mat$age_father_group_40, sep = "-")

# Summarize total count of children in each combined grid
summary_data_pat_40 <- filtered_data_pat %>%
  group_by(combined_group_40, mutationtype) %>%
  summarise(total_count = length(Pos))

summary_data_mat_40 <- filtered_data_mat %>%
  group_by(combined_group_40, mutationtype) %>%
  summarise(total_count = length(Pos))

#ggplot(filtered_data_pat, aes( x = AGE_FATHER, y = AGE_MOTHER, col = combined_group)) + geom_point() +
  #geom_vline(xintercept = age_father_bins, linetype = "solid", color = "gray") +
  #geom_hline(yintercept = age_mother_bins, linetype = "solid", color = "gray") +   theme_bw() +  # Set black and white theme
  #theme(legend.position = "none",  # Remove legend
        #axis.text = element_text(size = 8))  # Set smaller axis text size

length(unique(filtered_data_pat$combined_group_40))
min(summary_data_pat_40$total_count)
median(summary_data_pat_40$total_count)
max(summary_data_pat_40$total_count)
```


```{r}
# Constructing count matrix - paternal mutations ####

# Making a data set with count of each mutation type for each child
pat_data_40 <- filtered_data_pat %>% group_by(combined_group_40, mutationtype) %>% summarise(total_count = length(Pos))

# Making a matrix with rows = # children and cols = # mutation types (96)
pat_count_40 <- matrix(0, nrow = length(unique(filtered_data_pat$combined_group_40)), ncol = 96)

# Creating list of all 96 different mutation types
res <- permutations(4,2,c("A","C","G","T"), repeats.allowed = T, set = F)
res2 <- res[rep(1:nrow(res), 6),]
res2 <- cbind(res2,rep(sort(unique(filtered_data_pat$mutation_class_cpg)),each = nrow(res)))
res2 <- data.frame(res2)
res2$name <- paste0(res2$X1, "[", res2$X3, "]", res2$X2)

# Changing names of matrix to correspond to mutation types and child id
colnames(pat_count_40) <- res2$name
rownames(pat_count_40) <- sort(unique(filtered_data_pat$combined_group_40))

# Making the matrix with counts for paternal data
for (i in rownames(pat_count_40)){
  pat_count_40[i,pat_data_40$mutationtype[pat_data_40$combined_group_40==i]] <- pat_data_40$total_count[pat_data_40$combined_group_40==i]
}
saveRDS(pat_count_40, "CountMat_PaternalMutations_grouped_40.rds")
save(filtered_data_pat, file = "filtered_data_pat.RData")
```

```{r}
# Constructing count matrix - maternal mutations ####

# Making a data set with count of each mutation type for each child
mat_data_40 <- filtered_data_mat %>% group_by(combined_group_40, mutationtype) %>% summarise(total_count = length(Pos))

# Making a matrix with rows = # children and cols = # mutation types (96)
mat_count_40 <- matrix(0, nrow = length(unique(filtered_data_mat$combined_group_40)), ncol = 96)

# Creating list of all 96 different mutation types
res <- permutations(4,2,c("A","C","G","T"), repeats.allowed = T, set = F)
res2 <- res[rep(1:nrow(res), 6),]
res2 <- cbind(res2,rep(sort(unique(filtered_data_mat$mutation_class_cpg)),each = nrow(res)))
res2 <- data.frame(res2)
res2$name <- paste0(res2$X1, "[", res2$X3, "]", res2$X2)

# Changing names of matrix to correspond to mutation types and child id
colnames(mat_count_40) <- res2$name
rownames(mat_count_40) <- sort(unique(filtered_data_mat$combined_group_40))

# Making the matrix with counts for maternal data
for (i in rownames(mat_count_40)){
  mat_count_40[i,mat_data_40$mutationtype[mat_data_40$combined_group_40==i]] <- mat_data_40$total_count[mat_data_40$combined_group_40==i]
}
saveRDS(mat_count_40, "CountMat_MaternalMutations_grouped_40.rds")
save(filtered_data_mat, file = "filtered_data_mat.RData")
```



## Making the matrices with 119 groups!
```{r}
# As we have very small counts, we will divide the data into grids. Here for both types of mutations

# Create the bins for mother and father
age_mother_bins_pat_119 <- seq(min(filtered_data_pat$AGE_MOTHER)-1, max(filtered_data_pat$AGE_MOTHER)+5, by = 3)
age_father_bins_pat_119 <- seq(min(filtered_data_pat$AGE_FATHER)-1, max(filtered_data_pat$AGE_FATHER)+5, by = 3)

age_mother_bins_mat_119 <- seq(min(filtered_data_mat$AGE_MOTHER)-1, max(filtered_data_mat$AGE_MOTHER)+5, by = 3)
age_father_bins_mat_119 <- seq(min(filtered_data_mat$AGE_FATHER)-1, max(filtered_data_mat$AGE_FATHER)+5, by = 3)

# Cut age values into bins
filtered_data_pat$age_mother_group_119 <- cut(filtered_data_pat$AGE_MOTHER, breaks = age_mother_bins_pat_119, labels = FALSE)
filtered_data_pat$age_father_group_119 <- cut(filtered_data_pat$AGE_FATHER, breaks = age_father_bins_pat_119, labels = FALSE)

filtered_data_mat$age_mother_group_119 <- cut(filtered_data_mat$AGE_MOTHER, breaks = age_mother_bins_mat_119, labels = FALSE)
filtered_data_mat$age_father_group_119 <- cut(filtered_data_mat$AGE_FATHER, breaks = age_father_bins_mat_119, labels = FALSE)

# Now 'age_mother_group' and 'age_father_group' columns contain the group membership based on the grid

# Combine grid memberships from both age_mother_group and age_father_group columns
filtered_data_pat$combined_group_119 <- paste(filtered_data_pat$age_mother_group_119, filtered_data_pat$age_father_group_119, sep = "-")
filtered_data_mat$combined_group_119 <- paste(filtered_data_mat$age_mother_group_119, filtered_data_mat$age_father_group_119, sep = "-")

# Summarize total count of children in each combined grid
summary_data_pat_119 <- filtered_data_pat %>%
  group_by(combined_group_119, mutationtype) %>%
  summarise(total_count = length(Pos))

summary_data_mat_119 <- filtered_data_mat %>%
  group_by(combined_group_119, mutationtype) %>%
  summarise(total_count = length(Pos))

#ggplot(filtered_data_pat, aes( x = AGE_FATHER, y = AGE_MOTHER, col = combined_group)) + geom_point() +
  #geom_vline(xintercept = age_father_bins, linetype = "solid", color = "gray") +
  #geom_hline(yintercept = age_mother_bins, linetype = "solid", color = "gray") +   theme_bw() +  # Set black and white theme
  #theme(legend.position = "none",  # Remove legend
        #axis.text = element_text(size = 8))  # Set smaller axis text size

length(unique(filtered_data_pat$combined_group_119))
min(summary_data_pat_119$total_count)
median(summary_data_pat_119$total_count)
max(summary_data_pat_119$total_count)
```


```{r}
# Constructing count matrix - paternal mutations ####

# Making a data set with count of each mutation type for each child
pat_data_119 <- filtered_data_pat %>% group_by(combined_group_119, mutationtype) %>% summarise(total_count = length(Pos))

# Making a matrix with rows = # children and cols = # mutation types (96)
pat_count_119 <- matrix(0, nrow = length(unique(filtered_data_pat$combined_group_119)), ncol = 96)

# Creating list of all 96 different mutation types
res <- permutations(4,2,c("A","C","G","T"), repeats.allowed = T, set = F)
res2 <- res[rep(1:nrow(res), 6),]
res2 <- cbind(res2,rep(sort(unique(filtered_data_pat$mutation_class_cpg)),each = nrow(res)))
res2 <- data.frame(res2)
res2$name <- paste0(res2$X1, "[", res2$X3, "]", res2$X2)

# Changing names of matrix to correspond to mutation types and child id
colnames(pat_count_119) <- res2$name
rownames(pat_count_119) <- sort(unique(filtered_data_pat$combined_group_119))

# Making the matrix with counts for paternal data
for (i in rownames(pat_count_119)){
  pat_count_119[i,pat_data_119$mutationtype[pat_data_119$combined_group_119==i]] <- pat_data_119$total_count[pat_data_119$combined_group_119==i]
}
saveRDS(pat_count_119, "CountMat_PaternalMutations_grouped_119.rds")
save(filtered_data_pat, file = "filtered_data_pat.RData")
```

```{r}
# Constructing count matrix - maternal mutations ####

# Making a data set with count of each mutation type for each child
mat_data_119 <- filtered_data_mat %>% group_by(combined_group_119, mutationtype) %>% summarise(total_count = length(Pos))

# Making a matrix with rows = # children and cols = # mutation types (96)
mat_count_119 <- matrix(0, nrow = length(unique(filtered_data_mat$combined_group_119)), ncol = 96)

# Creating list of all 96 different mutation types
res <- permutations(4,2,c("A","C","G","T"), repeats.allowed = T, set = F)
res2 <- res[rep(1:nrow(res), 6),]
res2 <- cbind(res2,rep(sort(unique(filtered_data_mat$mutation_class_cpg)),each = nrow(res)))
res2 <- data.frame(res2)
res2$name <- paste0(res2$X1, "[", res2$X3, "]", res2$X2)

# Changing names of matrix to correspond to mutation types and child id
colnames(mat_count_119) <- res2$name
rownames(mat_count_119) <- sort(unique(filtered_data_mat$combined_group_119))

# Making the matrix with counts for maternal data
for (i in rownames(mat_count_119)){
  mat_count_119[i,mat_data_119$mutationtype[mat_data_119$combined_group_119==i]] <- mat_data_119$total_count[mat_data_119$combined_group_119==i]
}
saveRDS(mat_count_119, "CountMat_MaternalMutations_grouped_119.rds")
save(filtered_data_mat, file = "filtered_data_mat.RData")
```



For full data matrices

```{r}
# Constructing count matrix - maternal mutations ####

# Making a data set with count of each mutation type for each child
mat_data2 <- filtered_data_mat %>% group_by(Child, mutationtype) %>% summarise(total_count = length(Pos))

# Making a matrix with rows = # children and cols = # mutation types (96)
mat_count <- matrix(0, nrow = length(unique(filtered_data_mat$Child)), ncol = 96)

# Creating list of all 96 different mutation types
res <- permutations(4,2,c("A","C","G","T"), repeats.allowed = T, set = F)
res2 <- res[rep(1:nrow(res), 6),]
res2 <- cbind(res2,rep(sort(unique(filtered_data_mat$mutation_class_cpg)),each = nrow(res)))
res2 <- data.frame(res2)
res2$name <- paste0(res2$X1, "[", res2$X3, "]", res2$X2)

# Changing names of matrix to correspond to mutation types and child id
colnames(mat_count) <- res2$name
rownames(mat_count) <- sort(unique(filtered_data_mat$Child))

# Making the matrix with counts for maternal data
for (i in rownames(mat_count)){
  mat_count[i,mat_data2$mutationtype[mat_data2$Child==i]] <- mat_data2$total_count[mat_data2$Child==i]
}
saveRDS(mat_count, "CountMat_MaternalMutations.rds")
#sum(mat_count==0)/(nrow(mat_count)*ncol(mat_count))
#hist(rowSums(mat_count))
#mean(rowSums(mat_count))
```


```{r}
# Constructing count matrix - paternal mutations ####

# Making a data set with count of each mutation type for each child
pat_data2 <- filtered_data_pat %>% group_by(Child, mutationtype) %>% summarise(total_count = length(Pos))

# Making a matrix with rows = # children and cols = # mutation types (96)
pat_count <- matrix(0, nrow = length(unique(filtered_data_pat$Child)), ncol = 96)

# Creating list of all 96 different mutation types
res <- permutations(4,2,c("A","C","G","T"), repeats.allowed = T, set = F)
res2 <- res[rep(1:nrow(res), 6),]
res2 <- cbind(res2,rep(sort(unique(filtered_data_pat$mutation_class_cpg)),each = nrow(res)))
res2 <- data.frame(res2)
res2$name <- paste0(res2$X1, "[", res2$X3, "]", res2$X2)

# Changing names of matrix to correspond to mutation types and child id
colnames(pat_count) <- res2$name
rownames(pat_count) <- sort(unique(filtered_data_pat$Child))

# Making the matrix with counts for paternal data
for (i in rownames(pat_count)){
  pat_count[i,pat_data2$mutationtype[pat_data2$Child==i]] <- pat_data2$total_count[pat_data2$Child==i]
}
saveRDS(pat_count, "CountMat_PaternalMutations.rds")
# sum(pat_count==0)/(nrow(pat_count)*ncol(pat_count))
# hist(rowSums(pat_count))
```



